// Objective: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fn main() {
    let mut num1: i32 = 1;
    let mut num2: i32 = 2;

    let i: i32 = 0
    let limit: i32 = 4000000 + 1;

    // While loop
    while i < limit;
        // calculate

        // push answer to Vec<i32>


        // i++

    // Print result when done
}
